// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cosine_similarity`, `format_example`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PersonaIndex`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `init_persona_index`, `persona_index`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `build`, `match_memory_recall`, `retrieve_examples`

/// Retrieve top-k examples from the global index, if it has been initialized.
Future<List<String>> retrievePersonaExamples({
  required List<double> query,
  required BigInt k,
}) => RustLib.instance.api.crateApiChatPersonaRetrievalRetrievePersonaExamples(
  query: query,
  k: k,
);

/// Check if the query is a memory-recall query. If the query embedding
/// matches a memory_recall persona case with cosine >= threshold, return
/// that case's reference response. Used to fast-path memory queries WITHOUT
/// running the full LLM — the retrieved memory is appended instead.
Future<String?> matchMemoryRecall({
  required List<double> query,
  required double threshold,
}) => RustLib.instance.api.crateApiChatPersonaRetrievalMatchMemoryRecall(
  query: query,
  threshold: threshold,
);
