// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> auraCancel() => RustLib.instance.api.crateApiChatAuraCancel();

Stream<String> auraChat({required String prompt}) =>
    RustLib.instance.api.crateApiChatAuraChat(prompt: prompt);

Stream<String> auraChatChunked({required List<String> chunks}) =>
    RustLib.instance.api.crateApiChatAuraChatChunked(chunks: chunks);

Future<bool> auraPrefill({required String partial}) =>
    RustLib.instance.api.crateApiChatAuraPrefill(partial: partial);

Future<bool> auraInject({required String context}) =>
    RustLib.instance.api.crateApiChatAuraInject(context: context);

Future<bool> auraResetState() =>
    RustLib.instance.api.crateApiChatAuraResetState();
