// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> auraGetAvailableBackends() =>
    RustLib.instance.api.crateApiEngineAuraGetAvailableBackends();

Future<bool> auraSetBackend({required String backendName}) =>
    RustLib.instance.api.crateApiEngineAuraSetBackend(backendName: backendName);

Future<bool> auraSetThreads({required int threads}) =>
    RustLib.instance.api.crateApiEngineAuraSetThreads(threads: threads);

Future<bool> auraSetContextSize({required int nCtx}) =>
    RustLib.instance.api.crateApiEngineAuraSetContextSize(nCtx: nCtx);

Future<bool> auraClearMemory() =>
    RustLib.instance.api.crateApiEngineAuraClearMemory();

Future<bool> auraInit({
  required String modelPath,
  required String tokenizerPath,
  required String embedModelPath,
  required String embedTokPath,
}) => RustLib.instance.api.crateApiEngineAuraInit(
  modelPath: modelPath,
  tokenizerPath: tokenizerPath,
  embedModelPath: embedModelPath,
  embedTokPath: embedTokPath,
);
