// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chunk_text`, `handle_read_file_into_memory`

/// Read `path` (UTF-8 text, Markdown, source code, …) into AURA's vector memory.
///
/// - Reads the file, strips null/binary bytes for safety.
/// - Chunks into ~300-char passages preserving sentence/line boundaries.
/// - Embeds each chunk with the shared BgeTextEmbedder and stores in vec_memory.
/// - Returns `true` when ≥1 chunk was embedded, `false` on any early failure.
///
/// `label` is the human-readable source name injected as "From <label>: <chunk>".
/// If `None`, the file's basename is used. Pass a descriptive label so AURA can
/// say "From your research notes: …" instead of "From notes.md: …".
Future<bool> auraReadFileIntoMemory({required String path, String? label}) =>
    RustLib.instance.api.crateApiFileReadAuraReadFileIntoMemory(
      path: path,
      label: label,
    );
