// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.
//
// Manually patched to re-export subdirectory files so existing imports work.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

export 'memory/notes.dart';
export 'memory/proactive.dart';

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `database_file_empty`, `with_db_path_or_empty`, `worker_get_facts`, `worker_get_history`, `worker_get_summaries`

Future<String> auraGetAllNotebookTurns() =>
    RustLib.instance.api.crateApiMemoryAuraGetAllNotebookTurns();

Future<String> auraGetAllSummariesJson() =>
    RustLib.instance.api.crateApiMemoryAuraGetAllSummariesJson();

Future<String> auraGetAllFactsJson() =>
    RustLib.instance.api.crateApiMemoryAuraGetAllFactsJson();

/// Notebook "Insights" tab — durable synthesized understandings about the
/// user, ordered by confidence. `{id, kind, content, confidence,
/// evidence_count, source, timestamp}`.
Future<String> auraGetNotebookInsightsJson() =>
    RustLib.instance.api.crateApiMemoryAuraGetNotebookInsightsJson();

/// Notebook "Insights" tab — the RL proactive timeline (last 100 events).
/// `{id, trigger_id, label, trigger_type, engaged, timestamp}`.
Future<String> auraGetNotebookProactiveLogJson() =>
    RustLib.instance.api.crateApiMemoryAuraGetNotebookProactiveLogJson();

/// Notebook memory notes — user/pinned notes that are ALSO embedded into
/// vec_memory so RAG retrieves them forever. `{id, title, content, pinned,
/// timestamp}`.
Future<String> auraGetMemoryNotesJson() =>
    RustLib.instance.api.crateApiMemoryAuraGetMemoryNotesJson();

/// Semantic recall: embed the query and return the top-`limit` most relevant
/// memory strings from vec_memory. Used by the notebook "Related memories"
/// expandable. Falls back to empty string if the embedder isn't ready.
Future<String> auraSearchRelevant({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiMemoryAuraSearchRelevant(
  query: query,
  limit: limit,
);

Future<String> auraGetOverlayConfig() =>
    RustLib.instance.api.crateApiMemoryAuraGetOverlayConfig();

/// Ask the worker to check current system memory pressure and run the safe
/// auto-healer if needed. Returns a JSON status string with `pressure`,
/// `available_gb`, `total_gb`, `used_gb`, `did_heal`, and a friendly `message`.
/// The Flutter side can call this on a timer or whenever the OS reports low
/// memory, and show AURA's message instead of a generic "please close something
/// memory full" toast.
Future<String> auraCheckMemoryHealth() =>
    RustLib.instance.api.crateApiMemoryAuraCheckMemoryHealth();
