// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> auraSttInit() => RustLib.instance.api.crateApiSttAuraSttInit();

Future<String> auraSttPushAudio({
  required List<double> samples,
  required int sampleRate,
}) => RustLib.instance.api.crateApiSttAuraSttPushAudio(
  samples: samples,
  sampleRate: sampleRate,
);

Future<bool> auraSttAvailable() =>
    RustLib.instance.api.crateApiSttAuraSttAvailable();

Future<void> auraSttResetSession() =>
    RustLib.instance.api.crateApiSttAuraSttResetSession();
