// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<bool> auraTtsInit() => RustLib.instance.api.crateApiTtsAuraTtsInit();

Future<TtsAudio?> auraTtsSpeak({
  required String text,
  required double speed,
  required bool interrupt,
}) => RustLib.instance.api.crateApiTtsAuraTtsSpeak(
  text: text,
  speed: speed,
  interrupt: interrupt,
);

Future<bool> auraTtsStop() => RustLib.instance.api.crateApiTtsAuraTtsStop();

Future<void> auraTtsSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiTtsAuraTtsSetVolume(volume: volume);

Future<bool> auraTtsAvailable() =>
    RustLib.instance.api.crateApiTtsAuraTtsAvailable();

class TtsAudio {
  final Float32List samples;
  final int sampleRate;

  const TtsAudio({required this.samples, required this.sampleRate});

  @override
  int get hashCode => samples.hashCode ^ sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TtsAudio &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          sampleRate == other.sampleRate;
}
