// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../vision/events.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> auraProcessVision({required List<VisionDetection> detections}) =>
    RustLib.instance.api.crateApiVisionAuraProcessVision(
      detections: detections,
    );

/// Returns a pending webcam gesture label (e.g. "wave") if the webcam thread
/// detected one since the last call, then clears it. Empty string otherwise.
/// Dart polls this on a short timer to trigger immediate gesture greetings.
/// Each call also (re)starts/extends the headless gesture-watch session so the
/// camera stays alive for wave detection while the bar is polling.
Future<String> auraGetWebcamGesture() =>
    RustLib.instance.api.crateApiVisionAuraGetWebcamGesture();
