// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../memory/store/core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_memory_with_schedule_embedding`

/// Post-turn memory processing. No hardcoded extractors — the conversation
/// turn is stored in vec_memory by the caller via store_embed. The embedder
/// retrieves it naturally via cosine similarity when the user references a
/// past topic.
Future<List<String>> processMemory({
  required MemoryStore store,
  required String prompt,
  required String response,
}) => RustLib.instance.api.crateApiWorkerUtilsProcessMemory(
  store: store,
  prompt: prompt,
  response: response,
);
