// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<PlatformInt64> auraAddMemoryNote({
  required String title,
  required String content,
  required bool pinned,
}) => RustLib.instance.api.crateApiMemoryNotesAuraAddMemoryNote(
  title: title,
  content: content,
  pinned: pinned,
);

Future<bool> auraDeleteMemoryNote({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMemoryNotesAuraDeleteMemoryNote(id: id);

Future<bool> auraUpdateMemoryNote({
  required PlatformInt64 id,
  required String title,
  required String content,
  required bool pinned,
  required bool deleted,
}) => RustLib.instance.api.crateApiMemoryNotesAuraUpdateMemoryNote(
  id: id,
  title: title,
  content: content,
  pinned: pinned,
  deleted: deleted,
);

Future<bool> auraRecoverMemoryNote({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMemoryNotesAuraRecoverMemoryNote(id: id);

Future<bool> auraDeleteMemoryNotePermanently({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMemoryNotesAuraDeleteMemoryNotePermanently(
      id: id,
    );
