// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> auraGetBufferStatus() =>
    RustLib.instance.api.crateApiMemoryProactiveAuraGetBufferStatus();

Future<String> auraCheckProactive() =>
    RustLib.instance.api.crateApiMemoryProactiveAuraCheckProactive();

/// Compact recall block (facts / recent summary / recent turns / insights) for
/// proactive prompts. Returns an empty string when there is nothing to recall.
Future<String> auraGetProactiveContext() =>
    RustLib.instance.api.crateApiMemoryProactiveAuraGetProactiveContext();

Future<bool> auraRecordEngagement({
  required PlatformInt64 triggerId,
  required bool engaged,
}) => RustLib.instance.api.crateApiMemoryProactiveAuraRecordEngagement(
  triggerId: triggerId,
  engaged: engaged,
);

/// Record a proactive event in the RL timeline (visible in the notebook).
/// Called from the Dart scheduler/brain whenever a trigger fires + when its
/// outcome (engaged/ignored) is known. `trigger_type` is bandit/clock/idle/debug.
Future<bool> auraLogProactive({
  required PlatformInt64 triggerId,
  required String label,
  required String triggerType,
  required bool engaged,
}) => RustLib.instance.api.crateApiMemoryProactiveAuraLogProactive(
  triggerId: triggerId,
  label: label,
  triggerType: triggerType,
  engaged: engaged,
);
