// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineMsg`

Future<String> auraGetAllNotebookTurns() =>
    RustLib.instance.api.crateApiAuraGetAllNotebookTurns();

Future<bool> auraInit({
  required String modelPath,
  required String tokenizerPath,
}) => RustLib.instance.api.crateApiAuraInit(
  modelPath: modelPath,
  tokenizerPath: tokenizerPath,
);

Future<bool> auraInject({required String context}) =>
    RustLib.instance.api.crateApiAuraInject(context: context);

Stream<String> auraChat({required String prompt}) =>
    RustLib.instance.api.crateApiAuraChat(prompt: prompt);

Future<bool> auraPrefill({required String partial}) =>
    RustLib.instance.api.crateApiAuraPrefill(partial: partial);

Stream<String> auraChatChunked({required List<String> chunks}) =>
    RustLib.instance.api.crateApiAuraChatChunked(chunks: chunks);
