// Known/unavoidable warnings from autogenerated/dependency code.
#![allow(unexpected_cfgs)]

pub mod api;
pub mod config;
pub mod device_backend;
pub mod llama_engine;
pub mod memory;
pub(crate) mod memory_health;
pub mod performance_profile;
pub mod vision;

mod frb_generated;
