// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VisionDetection {
  final String label;
  final double confidence;
  final F32Array4? bbox;

  const VisionDetection({
    required this.label,
    required this.confidence,
    this.bbox,
  });

  @override
  int get hashCode => label.hashCode ^ confidence.hashCode ^ bbox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisionDetection &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          confidence == other.confidence &&
          bbox == other.bbox;
}
