part of 'vision_service.dart';

const List<String> _visionTriggerVocabulary = [
  'see',
  'look',
  'watch',
  'camera',
  'vision',
  'visual',
  'view',
  'visible',
  'observe',
  'observing',
  'peek',
  'scan',
  'inspect',
  'recognize',
  'detect',
  'identify',
  'what do you see',
  'what can you see',
  'can you see',
  'do you see',
  'did you see',
  'are you seeing',
  'look at me',
  'look around',
  'look here',
  'look now',
  'take a look',
  'have a look',
  'watch me',
  'watch this',
  'watch now',
  'use camera',
  'open camera',
  'check camera',
  'scan camera',
  'camera feed',
  'live camera',
  'webcam',
  'use webcam',
  'open webcam',
  'screen',
  'my screen',
  'on my screen',
  'what is on my screen',
  "what's on my screen",
  'look at my screen',
  'see my screen',
  'read my screen',
  'screen visible',
  'desktop',
  'window',
  'active window',
  'current window',
  'surroundings',
  'environment',
  'room',
  'desk',
  'background',
  'around me',
  'near me',
  'in front of me',
  'behind me',
  'wearing',
  'holding',
  'carrying',
  'doing',
  'what am i doing',
  "what i'm doing",
  'what i am doing',
  'what are you seeing',
  'what am i showing',
  'what is this',
  "what's this",
  'what is that',
  "what's that",
  'what object',
  'which object',
  'gesture',
  'hand',
  'wave',
  'waving',
  'thumbs up',
  'open palm',
  'face',
  'expression',
  'smile',
  'smiling',
  'person',
  'people',
  'motion',
  'movement',
  'changed',
  'scene',
  'scene change',
  'take a screenshot',
  'capture screen',
  'capture image',
  'snapshot',
  'screenshot',
  'analyze image',
  'analyse image',
  'visual context',
  'camera context',
  'screen context',
  'showing you',
  'i am showing',
  'can you tell what',
  'can you tell if',
];
